import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useContext } from "react";
import Categories from "~/components/content/categories";
import MainLayout from "~/components/layouts/main_layout";
import { userContext } from "~/contexts/UserProvider";
import { api } from "~/utils/api";

const CategoriesPage: NextPage = () => {
    const { data: session } = useSession();

    const { agent, agentType } = useContext(userContext);

    const categoriesMutation = api.category.getAgentCategories.useQuery(
        {
            agentId: agent?.id as string,
            agentType: agentType,
            prisma: false,
        },
        {
            enabled: !!agent?.id && !!agentType,
            cacheTime: 0,
        }
    );
    
    return (
        <>
            <Head>
                <title>JET</title>
                <meta name="description" content="Generated by create-t3-app" />
            </Head>
            <MainLayout>
                <Categories />
            </MainLayout>
        </>
    );
};

export default CategoriesPage;
