import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import MainLayout from "~/components/layouts/main_layout";

const Categories: NextPage = () => {

    const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>JET</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
        <MainLayout>
         <Categories />
        </MainLayout>
    </>
  );
};

export default Categories;
