import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Todos from "~/components/content/todos";

import NavBar from "~/components/navigation/nav_bar";
import Navigation from "~/components/navigation/navigation";

const Home: NextPage = () => {

    const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>JET</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col bg-[var(--primary-color)] text-white">
        <NavBar />
        {session?.user ? <Todos /> : <>NOT AUTHED</>}
        <Navigation />
      </main>
    </>
  );
};

export default Home;

