import { type NextPage } from "next";
import Head from "next/head";

import NavBar from "~/components/navigation/nav_bar";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gray-950 text-white">
        <NavBar />
      </main>
    </>
  );
};

export default Home;

